### ISSUE TITLE
Invalid public key generate

### ISSUE THREAD

**Issue by harshadkanziya-in** [miguelmota/ethereum-hdwallet#4]
I have add same example file code and check address and private key generate fine but public key is not correct generate 

mnemonic key : tag volcano eight thank tide danger coast health above argue embrace heavy
Address : 0xc49926c4124cee1cba0ea94ea31a6c12318df947
public key  : "6005c86a6718f66221713a77073c41291cc3abbfcd03aa4955e9b2b50dbf7f9b6672dad0d46ade61e382f79888a73ea7899d9419becf1d6c9ec2087c1188fa18" this key generate from code and it is wrong key 
correct key "0x026005c86a6718f66221713a77073c41291cc3abbfcd03aa4955e9b2b50dbf7f9b"
![Screenshot 2022-02-19 193330](https://user-images.githubusercontent.com/40978460/154804069-50ba9bb0-eac3-4eb3-bffe-d817db2284da.png)

can you please help for generate correct public key

**Comment by miguelmota** [comment]
Hi @harshadkanziya-in, thanks for the report. By default it returns the uncompressed public key. Set the compress boolean to true in `getPublicKey` method, e.g. `getPublicKey(true)`. This is available in latest version.

Example

```js
const HDWallet = require('ethereum-hdwallet')
const mnemonic = 'tag volcano eight thank tide danger coast health above argue embrace heavy'
const hdwallet = HDWallet.fromMnemonic(mnemonic)

console.log(`0x${hdwallet.derive(`m/44'/60'/0'/0/0`).getAddress().toString('hex')}`) // 0xc49926c4124cee1cba0ea94ea31a6c12318df947
console.log(`0x${hdwallet.derive(`m/44'/60'/0'/0/0`).getPublicKey(true).toString('hex')}`) // 0x026005c86a6718f66221713a77073c41291cc3abbfcd03aa4955e9b2b50dbf7f9b
console.log(`0x${hdwallet.derive(`m/44'/60'/0'/0/0`).getPrivateKey().toString('hex')}`) // 0x63e21d10fd50155dbba0e7d3f7431a400b84b4c2ac1ee38872f82448fe3ecfb9
```
